import type { Listing } from "@/types";

export const MOCK_LISTINGS: Listing[] = [
  {
    id: "l1",
    farmerId: "u1",
    farmerName: "Sipho Dlamini",
    farmerPhone: "+27821234567",
    title: "Fresh Mielies (Maize) — 200kg Surplus",
    category: "grains",
    description:
      "Yellow maize freshly harvested. Good eating quality. Surplus from this season's crop — must sell before end of week. Ideal for grain mills, animal feed, or bulk home cooking.",
    quantity: 200,
    unit: "kg",
    price: 3.5,
    currency: "ZAR",
    urgency: "high",
    location: { country: "ZA", province: "KwaZulu-Natal", city: "Pietermaritzburg" },
    photos: [
      "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800",
      "https://images.unsplash.com/photo-1604891803982-4e0c96f8d9b5?w=800",
    ],
    status: "active",
    views: 142,
    isFeatured: true,
    expiresAt: "2026-03-10T23:59:59Z",
    createdAt: "2026-03-05T08:00:00Z",
  },
  {
    id: "l2",
    farmerId: "u2",
    farmerName: "Grace Moyo",
    farmerPhone: "+263771234567",
    title: "Ripe Tomatoes — 5 Crates",
    category: "vegetables",
    description:
      "Fresh, ripe Roma tomatoes. Harvested today. 5 crates available. Perfect for restaurants, sauce production, or street food vendors. Must go — cannot store for more than 2 days.",
    quantity: 5,
    unit: "crate",
    price: 12,
    currency: "USD",
    urgency: "critical",
    location: { country: "ZW", province: "Mashonaland East", city: "Marondera" },
    photos: [
      "https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=800",
      "https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=800",
    ],
    status: "active",
    views: 89,
    isFeatured: true,
    expiresAt: "2026-03-08T23:59:59Z",
    createdAt: "2026-03-06T06:00:00Z",
  },
  {
    id: "l3",
    farmerId: "u3",
    farmerName: "Thabiso Nkosi",
    farmerPhone: "+27761234567",
    title: "Avocados — 3 Tons Surplus",
    category: "fruits",
    description:
      "Hass avocados at peak ripeness. 3 tonnes available after market allocation. Grade 2 fruit — still excellent for restaurants and home use. Price is per kg.",
    quantity: 3000,
    unit: "kg",
    price: 8,
    currency: "ZAR",
    urgency: "medium",
    location: { country: "ZA", province: "Limpopo", city: "Tzaneen" },
    photos: [
      "https://images.unsplash.com/photo-1519162808019-7de1683fa2ad?w=800",
    ],
    status: "active",
    views: 211,
    isFeatured: true,
    expiresAt: "2026-03-14T23:59:59Z",
    createdAt: "2026-03-04T09:00:00Z",
  },
  {
    id: "l4",
    farmerId: "u4",
    farmerName: "Nomsa Khumalo",
    farmerPhone: "+27831234567",
    title: "Free-range Chickens — 50 Head",
    category: "poultry",
    description:
      "Live free-range broiler chickens, 1.8–2.2kg each. Ready for slaughter. Selling surplus stock. Collection from farm in Nelspruit only.",
    quantity: 50,
    unit: "head",
    price: 85,
    currency: "ZAR",
    urgency: "high",
    location: { country: "ZA", province: "Mpumalanga", city: "Nelspruit" },
    photos: [
      "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800",
    ],
    status: "active",
    views: 67,
    isFeatured: false,
    expiresAt: "2026-03-11T23:59:59Z",
    createdAt: "2026-03-06T10:00:00Z",
  },
  {
    id: "l5",
    farmerId: "u5",
    farmerName: "Chiedza Murambwa",
    farmerPhone: "+263712345678",
    title: "Butternut Squash — 300kg",
    category: "vegetables",
    description:
      "Beautiful butternut squash from peri-urban Harare garden. Uniform size, excellent shelf life. Selling 300kg surplus. Delivery possible within Harare.",
    quantity: 300,
    unit: "kg",
    price: 0.8,
    currency: "USD",
    urgency: "low",
    location: { country: "ZW", province: "Harare Province", city: "Harare" },
    photos: [
      "https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=800",
    ],
    status: "active",
    views: 44,
    isFeatured: false,
    expiresAt: "2026-03-21T23:59:59Z",
    createdAt: "2026-03-03T08:00:00Z",
  },
  {
    id: "l6",
    farmerId: "u1",
    farmerName: "Sipho Dlamini",
    farmerPhone: "+27821234567",
    title: "Baby Spinach — 80kg",
    category: "vegetables",
    description:
      "Tender baby spinach, washed and packed in 500g bags. 80kg available. Perfect for restaurants and health food outlets. Harvested this morning.",
    quantity: 80,
    unit: "kg",
    price: 22,
    currency: "ZAR",
    urgency: "critical",
    location: { country: "ZA", province: "KwaZulu-Natal", city: "Pietermaritzburg" },
    photos: [
      "https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=800",
    ],
    status: "active",
    views: 93,
    isFeatured: false,
    expiresAt: "2026-03-08T23:59:59Z",
    createdAt: "2026-03-07T05:30:00Z",
  },
  {
    id: "l7",
    farmerId: "u3",
    farmerName: "Thabiso Nkosi",
    farmerPhone: "+27761234567",
    title: "Navel Oranges — 500kg",
    category: "fruits",
    description:
      "Sweet, juicy navel oranges from our Tzaneen grove. 500kg surplus after export grading. Selling at farm price. Ideal for juice bars, markets, and retailers.",
    quantity: 500,
    unit: "kg",
    price: 4,
    currency: "ZAR",
    urgency: "medium",
    location: { country: "ZA", province: "Limpopo", city: "Tzaneen" },
    photos: [
      "https://images.unsplash.com/photo-1547514701-42782101795e?w=800",
    ],
    status: "active",
    views: 158,
    isFeatured: true,
    expiresAt: "2026-03-17T23:59:59Z",
    createdAt: "2026-03-02T09:00:00Z",
  },
  {
    id: "l8",
    farmerId: "u2",
    farmerName: "Grace Moyo",
    farmerPhone: "+263771234567",
    title: "Green Cabbages — 2 Crates",
    category: "vegetables",
    description:
      "Large, firm green cabbages. 2 crates (approx 40 heads). Freshly cut. Available for pickup in Marondera town. Good price for quick sale.",
    quantity: 2,
    unit: "crate",
    price: 8,
    currency: "USD",
    urgency: "high",
    location: { country: "ZW", province: "Mashonaland East", city: "Marondera" },
    photos: [
      "https://images.unsplash.com/photo-1594282486552-05b4d80fbb9f?w=800",
    ],
    status: "active",
    views: 31,
    isFeatured: false,
    expiresAt: "2026-03-10T23:59:59Z",
    createdAt: "2026-03-06T07:00:00Z",
  },
  {
    id: "l9",
    farmerId: "u4",
    farmerName: "Nomsa Khumalo",
    farmerPhone: "+27831234567",
    title: "Goats for Sale — 12 Head",
    category: "livestock",
    description:
      "Healthy Boer goats, mixed ages. 12 head available. Currently grazing — need to reduce herd size. Price negotiable for bulk purchase. Collection only, Nelspruit farm.",
    quantity: 12,
    unit: "head",
    price: 1200,
    currency: "ZAR",
    urgency: "low",
    location: { country: "ZA", province: "Mpumalanga", city: "Nelspruit" },
    photos: [
      "https://images.unsplash.com/photo-1533318087102-b3ad366ed041?w=800",
    ],
    status: "active",
    views: 52,
    isFeatured: false,
    expiresAt: "2026-03-28T23:59:59Z",
    createdAt: "2026-02-28T10:00:00Z",
  },
  {
    id: "l10",
    farmerId: "u5",
    farmerName: "Chiedza Murambwa",
    farmerPhone: "+263712345678",
    title: "Fresh Herbs Bundle — 20kg Mixed",
    category: "herbs",
    description:
      "Mixed herb bundle: parsley, coriander, thyme, and basil. 20kg total (5kg each). Freshly cut from garden. Perfect for restaurant and hotel kitchens in Harare.",
    quantity: 20,
    unit: "kg",
    price: 3,
    currency: "USD",
    urgency: "critical",
    location: { country: "ZW", province: "Harare Province", city: "Harare" },
    photos: [
      "https://images.unsplash.com/photo-1466193249781-aad7c87ba7d4?w=800",
    ],
    status: "active",
    views: 72,
    isFeatured: false,
    expiresAt: "2026-03-08T23:59:59Z",
    createdAt: "2026-03-06T08:00:00Z",
  },
  {
    id: "l11",
    farmerId: "u1",
    farmerName: "Sipho Dlamini",
    farmerPhone: "+27821234567",
    title: "Sweet Potatoes — 150kg",
    category: "vegetables",
    description:
      "Orange-fleshed sweet potatoes, 150kg available. Farm-fresh, excellent condition. Sell within 2 weeks. Bulk discount available for 100kg+.",
    quantity: 150,
    unit: "kg",
    price: 6,
    currency: "ZAR",
    urgency: "medium",
    location: { country: "ZA", province: "KwaZulu-Natal", city: "Pietermaritzburg" },
    photos: [
      "https://images.unsplash.com/photo-1596097557993-54e1b2d3d626?w=800",
    ],
    status: "active",
    views: 61,
    isFeatured: false,
    expiresAt: "2026-03-19T23:59:59Z",
    createdAt: "2026-03-04T08:00:00Z",
  },
  {
    id: "l12",
    farmerId: "u2",
    farmerName: "Grace Moyo",
    farmerPhone: "+263771234567",
    title: "Onions — 4 Bags (50kg each)",
    category: "vegetables",
    description:
      "Red and white onions, mixed. 4 x 50kg bags. Well-cured, good shelf life. Surplus from market allocation. Selling at bulk discount. Pickup or delivery Marondera area.",
    quantity: 4,
    unit: "bag",
    price: 25,
    currency: "USD",
    urgency: "low",
    location: { country: "ZW", province: "Mashonaland East", city: "Marondera" },
    photos: [
      "https://images.unsplash.com/photo-1587735243615-c03f25aaff15?w=800",
    ],
    status: "active",
    views: 47,
    isFeatured: false,
    expiresAt: "2026-03-28T23:59:59Z",
    createdAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "l13",
    farmerId: "u3",
    farmerName: "Thabiso Nkosi",
    farmerPhone: "+27761234567",
    title: "Mangoes — 800kg Alphonso",
    category: "fruits",
    description:
      "Premium Alphonso mangoes at peak sweetness. 800kg available after export sorting. Selling fast — highly perishable. Great for juice, fresh eating, or desserts.",
    quantity: 800,
    unit: "kg",
    price: 9,
    currency: "ZAR",
    urgency: "critical",
    location: { country: "ZA", province: "Limpopo", city: "Tzaneen" },
    photos: [
      "https://images.unsplash.com/photo-1553279768-865429fa0078?w=800",
    ],
    status: "active",
    views: 183,
    isFeatured: true,
    expiresAt: "2026-03-09T23:59:59Z",
    createdAt: "2026-03-06T09:00:00Z",
  },
  {
    id: "l14",
    farmerId: "u4",
    farmerName: "Nomsa Khumalo",
    farmerPhone: "+27831234567",
    title: "Farm Fresh Eggs — 20 Dozen",
    category: "poultry",
    description:
      "Free-range eggs from our Mpumalanga flock. 20 dozen available weekly. Brown eggs, large size. Consistent supply possible. Contact for weekly order arrangement.",
    quantity: 20,
    unit: "dozen",
    price: 45,
    currency: "ZAR",
    urgency: "medium",
    location: { country: "ZA", province: "Mpumalanga", city: "Nelspruit" },
    photos: [
      "https://images.unsplash.com/photo-1582722872445-44dc5f7e3c8f?w=800",
    ],
    status: "active",
    views: 76,
    isFeatured: false,
    expiresAt: "2026-03-14T23:59:59Z",
    createdAt: "2026-03-05T07:00:00Z",
  },
  {
    id: "l15",
    farmerId: "u5",
    farmerName: "Chiedza Murambwa",
    farmerPhone: "+263712345678",
    title: "Leafy Greens Bundle — Rape & Chomolia",
    category: "vegetables",
    description:
      "Mixed leafy greens: rape (muriwo) and chomolia. 60kg available. Ideal for local restaurants and caterers. Harvested this morning, delivery possible in Harare CBD.",
    quantity: 60,
    unit: "kg",
    price: 1.5,
    currency: "USD",
    urgency: "critical",
    location: { country: "ZW", province: "Harare Province", city: "Harare" },
    photos: [
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800",
    ],
    status: "active",
    views: 55,
    isFeatured: false,
    expiresAt: "2026-03-08T23:59:59Z",
    createdAt: "2026-03-07T06:00:00Z",
  },
  {
    id: "l16",
    farmerId: "u1",
    farmerName: "Sipho Dlamini",
    farmerPhone: "+27821234567",
    title: "Pumpkins — 100 Units",
    category: "vegetables",
    description:
      "Large Crown Prince pumpkins, 100 available. Each 4–6kg. Good shelf life. Ideal for direct retail or wholesale. Farm collection, KwaZulu-Natal.",
    quantity: 100,
    unit: "kg",
    price: 12,
    currency: "ZAR",
    urgency: "low",
    location: { country: "ZA", province: "KwaZulu-Natal", city: "Pietermaritzburg" },
    photos: [
      "https://images.unsplash.com/photo-1570586437263-ab629fccc818?w=800",
    ],
    status: "active",
    views: 29,
    isFeatured: false,
    expiresAt: "2026-04-01T23:59:59Z",
    createdAt: "2026-03-02T08:00:00Z",
  },
  {
    id: "l17",
    farmerId: "u2",
    farmerName: "Grace Moyo",
    farmerPhone: "+263771234567",
    title: "Groundnuts (Peanuts) — 3 Bags",
    category: "grains",
    description:
      "Sun-dried groundnuts. 3 x 50kg bags. Clean and sorted. Ideal for peanut butter production, snack vendors, or oil pressing. Good shelf life.",
    quantity: 3,
    unit: "bag",
    price: 30,
    currency: "USD",
    urgency: "low",
    location: { country: "ZW", province: "Mashonaland East", city: "Marondera" },
    photos: [
      "https://images.unsplash.com/photo-1574202913168-12f49e7d5a35?w=800",
    ],
    status: "active",
    views: 68,
    isFeatured: false,
    expiresAt: "2026-04-05T23:59:59Z",
    createdAt: "2026-02-20T09:00:00Z",
  },
  {
    id: "l18",
    farmerId: "u3",
    farmerName: "Thabiso Nkosi",
    farmerPhone: "+27761234567",
    title: "Lemons — 400kg",
    category: "fruits",
    description:
      "Juicy Eureka lemons, 400kg. Bright yellow, highly fragrant. Surplus from contract shortfall. Ideal for juice bars, hotels, and restaurants. Sold per kg.",
    quantity: 400,
    unit: "kg",
    price: 5,
    currency: "ZAR",
    urgency: "medium",
    location: { country: "ZA", province: "Limpopo", city: "Tzaneen" },
    photos: [
      "https://images.unsplash.com/photo-1590502593747-42a996133562?w=800",
    ],
    status: "active",
    views: 84,
    isFeatured: false,
    expiresAt: "2026-03-17T23:59:59Z",
    createdAt: "2026-03-03T09:00:00Z",
  },
  {
    id: "l19",
    farmerId: "u4",
    farmerName: "Nomsa Khumalo",
    farmerPhone: "+27831234567",
    title: "Raw Cow Milk — 200 Litres",
    category: "dairy",
    description:
      "Fresh raw cow milk from grass-fed Jersey cows. 200 litres available each morning. Must be collected from Nelspruit farm by 7am. Consistent daily supply available.",
    quantity: 200,
    unit: "litre",
    price: 8,
    currency: "ZAR",
    urgency: "critical",
    location: { country: "ZA", province: "Mpumalanga", city: "Nelspruit" },
    photos: [
      "https://images.unsplash.com/photo-1550583724-b2692b85b150?w=800",
    ],
    status: "active",
    views: 119,
    isFeatured: false,
    expiresAt: "2026-03-08T23:59:59Z",
    createdAt: "2026-03-07T04:00:00Z",
  },
  {
    id: "l20",
    farmerId: "u5",
    farmerName: "Chiedza Murambwa",
    farmerPhone: "+263712345678",
    title: "Green Peppers — 60kg",
    category: "vegetables",
    description:
      "Crisp green peppers, 60kg. Freshly harvested from tunnel garden. Excellent quality. Ideal for restaurants and catering services. Delivery within Harare CBD possible.",
    quantity: 60,
    unit: "kg",
    price: 2,
    currency: "USD",
    urgency: "high",
    location: { country: "ZW", province: "Harare Province", city: "Harare" },
    photos: [
      "https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=800",
    ],
    status: "active",
    views: 41,
    isFeatured: false,
    expiresAt: "2026-03-11T23:59:59Z",
    createdAt: "2026-03-05T08:00:00Z",
  },
];
