import type { Transaction, Notification } from "@/types";

export const MOCK_TRANSACTIONS: Transaction[] = [
  {
    id: "t1",
    listingId: "l1",
    listingTitle: "Fresh Mielies (Maize) — 200kg Surplus",
    buyerId: "u6",
    buyerName: "Amahle Zulu",
    farmerId: "u1",
    farmerName: "Sipho Dlamini",
    amount: 700,
    currency: "ZAR",
    commissionRate: 5,
    commissionValue: 35,
    status: "completed",
    createdAt: "2026-02-14T10:00:00Z",
  },
  {
    id: "t2",
    listingId: "l7",
    listingTitle: "Navel Oranges — 500kg",
    buyerId: "u8",
    buyerName: "Lindiwe Mahlangu",
    farmerId: "u3",
    farmerName: "Thabiso Nkosi",
    amount: 2000,
    currency: "ZAR",
    commissionRate: 5,
    commissionValue: 100,
    status: "completed",
    createdAt: "2026-02-20T11:00:00Z",
  },
  {
    id: "t3",
    listingId: "l2",
    listingTitle: "Ripe Tomatoes — 5 Crates",
    buyerId: "u7",
    buyerName: "Tendai Chikwanda",
    farmerId: "u2",
    farmerName: "Grace Moyo",
    amount: 60,
    currency: "USD",
    commissionRate: 5,
    commissionValue: 3,
    status: "contacted",
    createdAt: "2026-03-01T09:00:00Z",
  },
  {
    id: "t4",
    listingId: "l3",
    listingTitle: "Avocados — 3 Tons Surplus",
    buyerId: "u9",
    buyerName: "Bongani Sithole",
    farmerId: "u3",
    farmerName: "Thabiso Nkosi",
    amount: 24000,
    currency: "ZAR",
    commissionRate: 5,
    commissionValue: 1200,
    status: "pending",
    createdAt: "2026-03-05T14:00:00Z",
  },
  {
    id: "t5",
    listingId: "l10",
    listingTitle: "Fresh Herbs Bundle — 20kg Mixed",
    buyerId: "u6",
    buyerName: "Amahle Zulu",
    farmerId: "u5",
    farmerName: "Chiedza Murambwa",
    amount: 60,
    currency: "USD",
    commissionRate: 5,
    commissionValue: 3,
    status: "completed",
    createdAt: "2026-02-28T08:00:00Z",
  },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: "n1",
    userId: "u1",
    type: "new_contact",
    title: "New buyer interested",
    message: "Amahle Zulu has contacted you about your Mielies listing.",
    isRead: false,
    href: "/dashboard/listings",
    createdAt: "2026-03-06T10:00:00Z",
  },
  {
    id: "n2",
    userId: "u1",
    type: "listing_expiring",
    title: "Listing expiring soon",
    message: "Your Baby Spinach listing expires in 24 hours.",
    isRead: false,
    href: "/dashboard/listings",
    createdAt: "2026-03-07T05:00:00Z",
  },
  {
    id: "n3",
    userId: "u6",
    type: "new_listing",
    title: "New listing in your area",
    message: "A new listing of Avocados was posted in Limpopo.",
    isRead: false,
    href: "/marketplace/l3",
    createdAt: "2026-03-04T09:00:00Z",
  },
  {
    id: "n4",
    userId: "u1",
    type: "listing_sold",
    title: "Listing marked as sold",
    message: "Your Mielies listing has been marked as sold. Great work!",
    isRead: true,
    href: "/dashboard/listings",
    createdAt: "2026-02-14T15:00:00Z",
  },
  {
    id: "n5",
    userId: "u6",
    type: "account_verified",
    title: "Account verified",
    message: "Your buyer account has been verified by ZeroWaste Farm.",
    isRead: true,
    createdAt: "2025-09-19T09:00:00Z",
  },
];
