import type { User } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "u1",
    name: "Sipho Dlamini",
    email: "sipho@farm.co.za",
    phone: "+27821234567",
    role: "farmer",
    location: { country: "ZA", province: "KwaZulu-Natal", city: "Pietermaritzburg" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Sipho",
    bio: "Third-generation farmer specialising in organic vegetables and maize.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-08-12T08:00:00Z",
  },
  {
    id: "u2",
    name: "Grace Moyo",
    email: "grace@zimfarm.co.zw",
    phone: "+263771234567",
    role: "farmer",
    location: { country: "ZW", province: "Mashonaland East", city: "Marondera" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Grace",
    bio: "Smallholder farmer growing tomatoes, onions, and leafy greens near Marondera.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-09-03T08:00:00Z",
  },
  {
    id: "u3",
    name: "Thabiso Nkosi",
    email: "thabiso@limpopofarm.co.za",
    phone: "+27761234567",
    role: "farmer",
    location: { country: "ZA", province: "Limpopo", city: "Tzaneen" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Thabiso",
    bio: "Citrus and avocado farmer with over 80 hectares in Tzaneen.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-07-20T08:00:00Z",
  },
  {
    id: "u4",
    name: "Nomsa Khumalo",
    email: "nomsa@farm.co.za",
    phone: "+27831234567",
    role: "farmer",
    location: { country: "ZA", province: "Mpumalanga", city: "Nelspruit" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Nomsa",
    bio: "Livestock and poultry farmer supplying fresh produce to local markets.",
    isVerified: false,
    isSuspended: false,
    createdAt: "2026-01-15T08:00:00Z",
  },
  {
    id: "u5",
    name: "Chiedza Murambwa",
    email: "chiedza@harare.co.zw",
    phone: "+263712345678",
    role: "farmer",
    location: { country: "ZW", province: "Harare Province", city: "Harare" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Chiedza",
    bio: "Urban farming specialist — leafy greens, herbs, and butternut squash.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-10-05T08:00:00Z",
  },
  {
    id: "u6",
    name: "Amahle Zulu",
    email: "amahle@restaurant.co.za",
    phone: "+27851234567",
    role: "buyer",
    location: { country: "ZA", province: "Gauteng", city: "Johannesburg" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Amahle",
    bio: "Head chef and sourcing manager for Roots Kitchen Restaurant group.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-09-18T08:00:00Z",
  },
  {
    id: "u7",
    name: "Tendai Chikwanda",
    email: "tendai@freshmart.co.zw",
    phone: "+263781234567",
    role: "buyer",
    location: { country: "ZW", province: "Bulawayo Province", city: "Bulawayo" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Tendai",
    bio: "Procurement officer for FreshMart grocery chain, Bulawayo.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-10-22T08:00:00Z",
  },
  {
    id: "u8",
    name: "Lindiwe Mahlangu",
    email: "lindiwe@streetfood.co.za",
    phone: "+27791234567",
    role: "buyer",
    location: { country: "ZA", province: "Gauteng", city: "Soweto" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Lindiwe",
    bio: "Street food vendor buying bulk produce for daily cooking.",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-11-10T08:00:00Z",
  },
  {
    id: "u9",
    name: "Bongani Sithole",
    email: "bongani@grocer.co.za",
    phone: "+27881234567",
    role: "buyer",
    location: { country: "ZA", province: "KwaZulu-Natal", city: "Durban" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Bongani",
    bio: "Owner of Sithole Fresh Produce market stall in Warwick Junction.",
    isVerified: false,
    isSuspended: false,
    createdAt: "2026-02-01T08:00:00Z",
  },
  {
    id: "u10",
    name: "Admin User",
    email: "admin@zerowaste.farm",
    phone: "+27001234567",
    role: "admin",
    location: { country: "ZA", province: "Gauteng", city: "Johannesburg" },
    profilePhoto: "https://api.dicebear.com/9.x/avataaars/svg?seed=Admin",
    isVerified: true,
    isSuspended: false,
    createdAt: "2025-06-01T08:00:00Z",
  },
];

// Quick-access demo credentials per role
export const DEMO_CREDENTIALS = {
  farmer: { email: "sipho@farm.co.za", password: "demo1234" },
  buyer: { email: "amahle@restaurant.co.za", password: "demo1234" },
  admin: { email: "admin@zerowaste.farm", password: "demo1234" },
};
